### ISSUE TITLE
support node v10.x

### ISSUE THREAD

**Issue by binyamin** [Eyal-Shalev/docopt.js#1]
First, great project. To be honest, I haven't used it yet, but I think it's a wonderful concept.

In the readme, the supported nodejs version is `>=12.16.0`. While most people probably use the most recent LTS, node v10 is still officially supported by the Node.js working group (<https://github.com/nodejs/Release>). I would recommend dropping support down to v10.x.

**Comment by binyamin** [comment]
Some more things :grin:
- maybe publish on npm?
- is this library typescript-only?

**Comment by Eyal-Shalev** [comment]
- It only supports `node >= 12.16.0` because that is when they added support for the import statement.  
   Which I wanted to use because, I also want to support `deno`.
- maybe publish on npm?  
   This is an implementation of [docopt](https://github.com/docopt) and the plan is to publish it on NPM after it is moved under the docopt organization.

   _Note: If I'll see that this is not going to happen, then I'll probably publish it under my own name and add a mention to the original author._

- is this library typescript-only?
   I started writing in typescript, but they caused me some headaches with their import system (they don't allow file extensions, and when compiling the code they don't add the correct file extensions either - it's a mess).  
   So I ended up writing with the latest features of ECMA Script.

Finally, thanks for the interest and I hope that this library will serve you nicely 😀

**Comment by Eyal-Shalev** [comment]
@b3u 

After further considerations, I re-added typescript support with CommonJS (node 10) support, alongside ES-modules support.
If you want, I could add you as reviewer for it.

https://github.com/Eyal-Shalev/docopt.js/tree/typescript

**Comment by Eyal-Shalev** [comment]
Done
